### ISSUE TITLE
Antipattern: "listener is passed the response object as it's context" ?

### ISSUE THREAD

**Issue by kapouer** [jshttp/on-headers#6]
Hi,
granted this is a little rhetorical, but what if the listener is a bounded instance method ?
Usually `listener(res)` would be a better interface.

**Comment by dougwilson** [comment]
This is because it follows event emitter pattern. For example, this is is how you should imagine using this module, once it I in core:

    res.on('headers', function(){
      this.setHeader(...)
    })
